[package]
authors = ["Brian Jewkes <bdjewkes@gmail.com>"]
name = "gameserver"
version = "0.1.0"

[dependencies]
rocket = ""
rocket_codegen = ""
rocket_contrib = ""
serde = ""
serde_derive = ""
serde_json = ""
ws = { git = "https://github.com/housleyjk/ws-rs" }
